
package com.soap.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TextCasingSoapType", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TextCasingSoapType {


    /**
     * 
     * @param sToken
     * @param sText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TitleCaseWordsWithToken")
    @WebResult(name = "TitleCaseWordsWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "TitleCaseWordsWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.TitleCaseWordsWithToken")
    @ResponseWrapper(localName = "TitleCaseWordsWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.TitleCaseWordsWithTokenResponse")
    public String titleCaseWordsWithToken(
        @WebParam(name = "sText", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sText,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sToken);

    /**
     * Uppercase letters that are lowercase and lowercase letters that are uppercase.
     * 
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InvertStringCase")
    @WebResult(name = "InvertStringCaseResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "InvertStringCase", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.InvertStringCase")
    @ResponseWrapper(localName = "InvertStringCaseResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.InvertStringCaseResponse")
    public String invertStringCase(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString);

    /**
     * Invert the casing of the first letter and adjust the string to conform with the previous casing of first letter.
     * 
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InvertCaseFirstAdjustStringToPrevious")
    @WebResult(name = "InvertCaseFirstAdjustStringToPreviousResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "InvertCaseFirstAdjustStringToPrevious", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.InvertCaseFirstAdjustStringToPrevious")
    @ResponseWrapper(localName = "InvertCaseFirstAdjustStringToPreviousResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.InvertCaseFirstAdjustStringToPreviousResponse")
    public String invertCaseFirstAdjustStringToPrevious(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString);

    /**
     * Invert the casing of the first letter and adjust the string to conform with the current casing of first letter.
     * 
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InvertCaseFirstAdjustStringToCurrent")
    @WebResult(name = "InvertCaseFirstAdjustStringToCurrentResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "InvertCaseFirstAdjustStringToCurrent", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.InvertCaseFirstAdjustStringToCurrent")
    @ResponseWrapper(localName = "InvertCaseFirstAdjustStringToCurrentResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.InvertCaseFirstAdjustStringToCurrentResponse")
    public String invertCaseFirstAdjustStringToCurrent(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString);

    /**
     * Change string to uppercase adding token between characters.
     * 
     * @param sToken
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AllUppercaseWithToken")
    @WebResult(name = "AllUppercaseWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "AllUppercaseWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.AllUppercaseWithToken")
    @ResponseWrapper(localName = "AllUppercaseWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.AllUppercaseWithTokenResponse")
    public String allUppercaseWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sToken);

    /**
     * Change string to lowercase adding token between characters.
     * 
     * @param sToken
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AllLowercaseWithToken")
    @WebResult(name = "AllLowercaseWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "AllLowercaseWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.AllLowercaseWithToken")
    @ResponseWrapper(localName = "AllLowercaseWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.AllLowercaseWithTokenResponse")
    public String allLowercaseWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sToken);

    /**
     * Change string to uppercase adding token between characters of each word.
     * 
     * @param sToken
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UppercaseWordsWithToken")
    @WebResult(name = "UppercaseWordsWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "UppercaseWordsWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.UppercaseWordsWithToken")
    @ResponseWrapper(localName = "UppercaseWordsWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.UppercaseWordsWithTokenResponse")
    public String uppercaseWordsWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sToken);

    /**
     * Change string to lowercase adding token between characters of each word.
     * 
     * @param sToken
     * @param sAString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LowercaseWordsWithToken")
    @WebResult(name = "LowercaseWordsWithTokenResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
    @RequestWrapper(localName = "LowercaseWordsWithToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.LowercaseWordsWithToken")
    @ResponseWrapper(localName = "LowercaseWordsWithTokenResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.soap.ws.client.LowercaseWordsWithTokenResponse")
    public String lowercaseWordsWithToken(
        @WebParam(name = "sAString", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sAString,
        @WebParam(name = "sToken", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        String sToken);

}
